In [1]:
import jax.numpy as jnp
from jax import config
config.update("jax_enable_x64", True)
import pandas as pd


In [2]:
seq_df = pd.read_csv('seq_all_samples_nonlinear_ct_euler.csv')

In [3]:
seq=jnp.array(seq_df)[:,1:]

In [4]:
var_seq= jnp.var(seq, axis=1, ddof=1)

In [5]:
var_seq

Array([6.16705579e-07, 7.93065765e-05, 4.89468029e-04, 6.29374712e-03,
       1.57174296e-03, 2.27390939e-01, 7.82920486e-02, 1.80435976e+01],      dtype=float64)

In [6]:
par_df = pd.read_csv('par_all_samples_nonlinear_ct_euler.csv')

In [7]:
par=jnp.array(par_df)[:,1:]

In [8]:
var_par = jnp.var(par, axis=1, ddof=1)

In [9]:
var_par

Array([8.45113760e-07, 6.75696227e-07, 4.95907126e-06, 2.04640689e-06,
       5.00004369e-08, 6.73610240e-09, 2.49616309e-08, 4.54983087e-08],      dtype=float64)

In [10]:
par_time_std_arr = jnp.std(jnp.array(par), axis=1, ddof=1)
seq_time_std_arr = jnp.std(jnp.array(seq), axis=1, ddof=1)

In [11]:
seq_time_std_arr

Array([7.85306042e-04, 8.90542399e-03, 2.21239244e-02, 7.93331401e-02,
       3.96452136e-02, 4.76855260e-01, 2.79807163e-01, 4.24777560e+00],      dtype=float64)

In [12]:
par_time_std_arr

Array([9.19300691e-04, 8.22007437e-04, 2.22689723e-03, 1.43052679e-03,
       2.23607775e-04, 8.20737620e-05, 1.57992503e-04, 2.13303326e-04],      dtype=float64)