In [1]:
import jax.numpy as jnp
from jax import config
config.update("jax_enable_x64", True)
import pandas as pd


In [2]:
seq_df = pd.read_csv('seq_all_samples_linear_wv_euler_tfs.csv')

In [3]:
seq_extra_blocks=jnp.array(seq_df)[:,1:] 

In [4]:
seq=seq_extra_blocks[::20]

In [5]:
seq.shape

(8, 20)

In [6]:
var_seq= jnp.var(seq[:,1:], axis=1, ddof=1)

In [7]:
par_df = pd.read_csv('par_all_samples_linear_wv_euler_tfs.csv')

In [8]:
par=jnp.array(par_df)[:,1:]

In [9]:
var_par = jnp.var(par, axis=1, ddof=1)

In [10]:
var_par

Array([1.50187426e-08, 1.94655589e-08, 2.63242174e-07, 5.21612254e-07,
       8.80703931e-07, 7.29016856e-07, 2.21435115e-06, 1.40797438e-07],      dtype=float64)

In [11]:
par_time_std_arr = jnp.std(jnp.array(par), axis=1, ddof=1)
seq_time_std_arr = jnp.std(jnp.array(seq), axis=1, ddof=1)

In [12]:
seq_time_std_arr

Array([0.00199092, 0.00581137, 0.0015552 , 0.00364464, 0.08363876,
       0.0942194 , 0.32091652, 1.26706047], dtype=float64)

In [13]:
par_time_std_arr

Array([0.00012255, 0.00013952, 0.00051307, 0.00072223, 0.00093846,
       0.00085382, 0.00148807, 0.00037523], dtype=float64)