In [1]:
import jax.numpy as jnp
from jax import config
config.update("jax_enable_x64", True)
import pandas as pd


In [2]:
seq_df = pd.read_csv('seq_all_samples_linear_wv_euler.csv')

In [3]:
seq=jnp.array(seq_df)[:,1:]

In [4]:
var_seq= jnp.var(seq, axis=1, ddof=1)

In [5]:
var_seq

Array([9.71540774e-07, 9.90932883e-06, 1.37431852e-04, 7.22415939e-04,
       7.88499927e-05, 4.64281577e-03, 2.86294554e-03, 1.14494684e-01],      dtype=float64)

In [6]:
par_df = pd.read_csv('par_all_samples_linear_wv_euler.csv')

In [7]:
par=jnp.array(par_df)[:,1:]

In [8]:
var_par = jnp.var(par, axis=1, ddof=1)

In [9]:
var_par

Array([6.51328931e-09, 1.00385655e-06, 1.16145629e-06, 8.17012281e-07,
       2.49740072e-06, 9.87570537e-07, 8.70932067e-09, 2.14316838e-08],      dtype=float64)

In [10]:
par_time_std_arr = jnp.std(jnp.array(par), axis=1, ddof=1)
seq_time_std_arr = jnp.std(jnp.array(seq), axis=1, ddof=1)

In [11]:
seq_time_std_arr

Array([0.00098567, 0.00314791, 0.01172313, 0.0268778 , 0.00887975,
       0.06813821, 0.0535065 , 0.33837063], dtype=float64)

In [12]:
par_time_std_arr

Array([8.07049522e-05, 1.00192642e-03, 1.07770882e-03, 9.03887317e-04,
       1.58031665e-03, 9.93765836e-04, 9.33237412e-05, 1.46395641e-04],      dtype=float64)